// lib/data.ts
import type { Exercise } from "./types"

// Shared constants (used inside the array)
export const ALL_POSITIONS = ["standard", "reverse", "giant", "giantReverse"] as const
const EQUIP_ALL = ["Micro", "Micro Pro", "Mini", "Mini Pro", "Mega", "Mega Pro", "Megaformer"] as const
const EQ = [...EQUIP_ALL]
const EQ_FLOOR = ["Floor"] as const
const EQ_NONE = ["None"] as const

export const lagreeExercises: Exercise[] = [
 
  // =========================
  // PLANK / WHEELBARROW FAMILY
  // =========================
  {
    id: "ex_elevated_plank",
    name: "Elevated Plank (The Plank)",
    description: "High plank; shoulders stacked, ribs in, slow carriage control.",
    muscleGroups: ["core", "arms"],
    series: "Plank",
    defaultMetric: "time",
    defaultTimeSec: 60,
    equipment: EQ,
    level: "beginner",
    supportedPositions: [...ALL_POSITIONS],
    aliases: ["The Plank", "High Plank"],
  },
  {
    id: "ex_kneeling_plank",
    name: "Kneeling / Modified Plank (Wheelbarrow Position)",
    description: "Hands front platform, knees on carriage; maintain neutral spine.",
    muscleGroups: ["core", "arms"],
    series: "Plank",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "beginner",
    supportedPositions: [...ALL_POSITIONS],
    aliases: ["Modified Plank"],
  },
  {
    id: "ex_plank_elbow_feet",
    name: "Plank on Elbows and Feet",
    description: "Elbows under shoulders; glutes engaged; strong rib-to-hip connection.",
    muscleGroups: ["core"],
    series: "Plank",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_plank_elbow_knee",
    name: "Plank on Elbows and Knee",
    description: "Modified forearm plank; prioritize spinal neutrality and breath.",
    muscleGroups: ["core"],
    series: "Plank",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "beginner",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_plank_to_pike",
    name: "Plank to Pike",
    description: "From plank, lift hips to pike pulling carriage with the core; slow return.",
    muscleGroups: ["core"],
    series: "Plank",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
    aliases: ["P2P", "Plank Pike"],
  },
  {
    id: "ex_reverse_elevated_plank",
    name: "Reverse Elevated Plank",
    description: "Facing back; shoulders open, hips high; posterior chain focus.",
    muscleGroups: ["core", "back"],
    series: "Plank",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
    aliases: ["Reverse Plank"],
  },
  {
    id: "ex_reverse_giant_elevated_plank",
    name: "Reverse Giant Elevated Plank",
    description: "Back platform orientation with extended lever; emphasize shoulder stability.",
    muscleGroups: ["core", "back", "arms"],
    series: "Plank",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "advanced",
    supportedPositions: [...ALL_POSITIONS],
    aliases: ["Giant Reverse Elevated Plank"],
  },
  {
    id: "ex_giant_elevated_plank",
    name: "Giant Elevated Plank",
    description: "Back platform facing front; longer lever increases core demand.",
    muscleGroups: ["core", "arms"],
    series: "Plank",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "advanced",
    supportedPositions: [...ALL_POSITIONS],
  },

  // Wheelbarrow + compare drill
  {
    id: "ex_wheelbarrow",
    name: "Wheelbarrow",
    description: "Hands front platform, knees or toes on carriage; protract shoulders and move slow.",
    muscleGroups: ["core", "arms"],
    series: "Wheelbarrow",
    defaultMetric: "time",
    defaultTimeSec: 60,
    equipment: EQ,
    level: "beginner",
    supportedPositions: [...ALL_POSITIONS],
    aliases: ["WB"],
  },
  {
    id: "ex_reverse_wheelbarrow",
    name: "Reverse Wheelbarrow",
    description: "Reverse orientation; maintain rib connection and neutral wrists.",
    muscleGroups: ["core", "arms"],
    series: "Wheelbarrow",
    defaultMetric: "time",
    defaultTimeSec: 60,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_reverse_giant_wheelbarrow",
    name: "Reverse Giant Wheelbarrow",
    description: "Back platform + reverse facing; slower tempo, strong shoulder pack.",
    muscleGroups: ["core", "arms"],
    series: "Wheelbarrow",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "advanced",
    supportedPositions: [...ALL_POSITIONS],
    aliases: ["Giant Reverse Wheelbarrow"],
  },
  {
    id: "ex_giant_wheelbarrow",
    name: "Giant Wheelbarrow",
    description: "Back platform facing front; long lever challenge to lats and core.",
    muscleGroups: ["core", "arms", "back"],
    series: "Wheelbarrow",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "advanced",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_saw_vs_wheelbarrow",
    name: "Saw vs Wheelbarrow (Compare Drill)",
    description: "Contrast scapular glide in Saw with shoulder protraction in Wheelbarrow.",
    muscleGroups: ["core", "arms"],
    series: "Wheelbarrow",
    defaultMetric: "time",
    defaultTimeSec: 60,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
    tags: ["drill", "education"],
  },

  // Saw
  {
    id: "ex_saw_elbows_knees",
    name: "Saw on Elbows and Knees",
    description: "Forearms down; knee support; glide carriage via shoulder motion.",
    muscleGroups: ["core", "back"],
    series: "Saw",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "beginner",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_saw_elbows_feet",
    name: "Saw on Elbows and Feet",
    description: "Forearms plank; feet on carriage; long, slow shoulder glide.",
    muscleGroups: ["core", "back"],
    series: "Saw",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_reverse_saw_elbows_feet",
    name: "Reverse Saw on Elbows and Feet",
    description: "Reverse orientation increases anterior chain challenge.",
    muscleGroups: ["core", "back"],
    series: "Saw",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_reverse_giant_saw_elbows_feet",
    name: "Reverse Giant Saw on Elbows and Feet",
    description: "Back platform + reverse; extra lever length, slow and controlled.",
    muscleGroups: ["core", "back"],
    series: "Saw",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "advanced",
    supportedPositions: [...ALL_POSITIONS],
    aliases: ["Giant Reverse Saw"],
  },
  {
    id: "ex_giant_saw_elbows_feet",
    name: "Giant Saw on Elbows and Feet",
    description: "Back platform facing front; lats and serratus under TUT.",
    muscleGroups: ["core", "back"],
    series: "Saw",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "advanced",
    supportedPositions: [...ALL_POSITIONS],
  },

  // Bear & Catfish
  {
    id: "ex_bear",
    name: "Bear",
    description: "Knees track under hips; neutral spine; slow in/slow out.",
    muscleGroups: ["core"],
    series: "Bear",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "beginner",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_reverse_bear",
    name: "Reverse Bear",
    description: "Reverse orientation; watch wrist angles; brace core.",
    muscleGroups: ["core"],
    series: "Bear",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_reverse_giant_bear",
    name: "Reverse Giant Bear",
    description: "Back platform facing back; longer lever challenges trunk control.",
    muscleGroups: ["core"],
    series: "Bear",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "advanced",
    supportedPositions: [...ALL_POSITIONS],
    aliases: ["Giant Reverse Bear"],
  },
  {
    id: "ex_giant_bear",
    name: "Giant Bear",
    description: "Back platform facing front; deep core + shoulder stability.",
    muscleGroups: ["core"],
    series: "Bear",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "advanced",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_bear_vs_catfish",
    name: "Bear vs Catfish (Compare Drill)",
    description: "Contrast hip/knee path in Bear with spinal articulation in Catfish.",
    muscleGroups: ["core"],
    series: "Bear",
    defaultMetric: "time",
    defaultTimeSec: 60,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
    tags: ["drill", "education"],
  },

  {
    id: "ex_catfish",
    name: "Catfish",
    description: "C-curve spinal flexion; scoop ribs to hips; smooth tempo.",
    muscleGroups: ["core"],
    series: "Catfish",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_reverse_giant_catfish",
    name: "Reverse Giant Catfish",
    description: "Back platform + reverse; emphasize segmental flexion.",
    muscleGroups: ["core"],
    series: "Catfish",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "advanced",
    supportedPositions: [...ALL_POSITIONS],
    aliases: ["Giant Reverse Catfish"],
  },

  // Pushing against the tension
  {
    id: "ex_mega_catfish",
    name: "Mega Catfish",
    description: "Heavier spring; strong C-curve and controlled return.",
    muscleGroups: ["core"],
    series: "Pushing Against the Tension",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "advanced",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_ice_breaker",
    name: "Ice Breaker",
    description: "Power-oriented push against spring; keep shoulders packed.",
    muscleGroups: ["core", "arms"],
    series: "Pushing Against the Tension",
    defaultMetric: "time",
    defaultTimeSec: 30,
    equipment: EQ,
    level: "advanced",
    supportedPositions: [...ALL_POSITIONS],
    tags: ["power"],
  },

  // =========================
  // LUNGES (incl. minis) + HOW TO INTENSIFY DRILLS
  // =========================
  {
    id: "ex_elevator_lunge",
    name: "Elevator Lunge",
    description: "Front platform; pulse up/down through controlled ranges.",
    muscleGroups: ["legs", "glutes", "quads"],
    series: "Lunge",
    unilateral: true,
    defaultMetric: "time",
    defaultTimeSec: 60,
    equipment: EQ,
    level: "beginner",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_elevator_lunge_kicks",
    name: "Elevator Lunge: Carriage Kicks",
    description: "Hold depth; small controlled carriage kicks.",
    muscleGroups: ["legs", "glutes", "quads"],
    series: "Lunge",
    unilateral: true,
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_escalator_lunge",
    name: "Escalator Lunge",
    description: "Back-facing slow descent/ascent; knee stacks over ankle.",
    muscleGroups: ["legs", "glutes", "quads"],
    series: "Lunge",
    unilateral: true,
    defaultMetric: "time",
    defaultTimeSec: 60,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_escalator_lunge_kicks",
    name: "Escalator Lunge: Carriage Kicks",
    description: "Maintain lunge depth while pulsing the carriage.",
    muscleGroups: ["legs", "glutes", "quads"],
    series: "Lunge",
    unilateral: true,
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_xpress_lunge",
    name: "Xpress Lunge",
    description: "Shorter range, quicker tempo; strict knee tracking.",
    muscleGroups: ["legs", "glutes", "quads"],
    series: "Lunge",
    unilateral: true,
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
    aliases: ["Express Lunge", "Xpress"],
  },
  {
    id: "ex_xpress_lunge_kicks",
    name: "Xpress Lunge: Carriage Kicks",
    description: "Quicker pulses in a stable base; maintain torso angle.",
    muscleGroups: ["legs", "glutes", "quads"],
    series: "Lunge",
    unilateral: true,
    defaultMetric: "time",
    defaultTimeSec: 40,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_fifth_lunge",
    name: "5th Lunge",
    description: "Advanced foot/knee path; tiny, precise ranges.",
    muscleGroups: ["legs", "glutes", "quads"],
    series: "Lunge",
    unilateral: true,
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "advanced",
    supportedPositions: [...ALL_POSITIONS],
    aliases: ["Fifth Lunge"],
  },
  {
    id: "ex_fifth_lunge_kicks",
    name: "5th Lunge: Carriage Kicks",
    description: "Hold fifth foot position; micro kicks with control.",
    muscleGroups: ["legs", "glutes", "quads"],
    series: "Lunge",
    unilateral: true,
    defaultMetric: "time",
    defaultTimeSec: 40,
    equipment: EQ,
    level: "advanced",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_floor_lunge",
    name: "Floor Lunge",
    description: "Off-machine lunge variant; coach alignment and control.",
    muscleGroups: ["legs", "glutes", "quads"],
    series: "Lunge",
    unilateral: true,
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ_FLOOR,
    level: "beginner",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_super_lunge",
    name: "Super Lunge",
    description: "Large range, long lever; strong hip/ankle control.",
    muscleGroups: ["legs", "glutes", "quads"],
    series: "Lunge",
    unilateral: true,
    defaultMetric: "time",
    defaultTimeSec: 60,
    equipment: EQ,
    level: "advanced",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_runners_lunge",
    name: "Runner's Lunge",
    description: "Long stride; torso hinge; drive through front heel.",
    muscleGroups: ["legs", "glutes", "hamstrings"],
    series: "Lunge",
    unilateral: true,
    defaultMetric: "time",
    defaultTimeSec: 60,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
    aliases: ["Runners Lunge"],
  },
  {
    id: "ex_spider_lunge",
    name: "Spider Lunge",
    description: "External rotation; keep knee tracking with foot.",
    muscleGroups: ["legs", "glutes", "obliques"],
    series: "Lunge",
    unilateral: true,
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "advanced",
    supportedPositions: [...ALL_POSITIONS],
  },

  // Monorail vs Dual rail + Mini lunges
  {
    id: "ex_monorail_vs_dual",
    name: "Monorail Lunges vs Dual Rail Lunges",
    description: "Teaching drill comparing stability demands and carriage path.",
    muscleGroups: ["legs", "glutes"],
    series: "Monorail Lunges",
    defaultMetric: "time",
    defaultTimeSec: 60,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
    tags: ["drill", "education"],
  },
  {
    id: "ex_mini_elevator",
    name: "Mini Elevator",
    description: "Compact elevator pulses; emphasize time-under-tension.",
    muscleGroups: ["legs", "glutes", "quads"],
    series: "Monorail Lunges",
    unilateral: true,
    defaultMetric: "time",
    defaultTimeSec: 40,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_mini_escalator",
    name: "Mini Escalator",
    description: "Small-range escalator patterns with meticulous control.",
    muscleGroups: ["legs", "glutes", "quads"],
    series: "Monorail Lunges",
    unilateral: true,
    defaultMetric: "time",
    defaultTimeSec: 40,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_mini_xpress",
    name: "Mini Xpress",
    description: "Short range, slightly quicker pulses; form priority.",
    muscleGroups: ["legs", "glutes", "quads"],
    series: "Monorail Lunges",
    unilateral: true,
    defaultMetric: "time",
    defaultTimeSec: 35,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
    aliases: ["Mini Express"],
  },
  {
    id: "ex_filthy_mini_5th",
    name: "Filthy (Mini 5th)",
    description: "Micro 5th-lunge pulses; advanced knee/foot path control.",
    muscleGroups: ["legs", "glutes", "quads"],
    series: "Monorail Lunges",
    unilateral: true,
    defaultMetric: "time",
    defaultTimeSec: 35,
    equipment: EQ,
    level: "advanced",
    supportedPositions: [...ALL_POSITIONS],
    aliases: ["Mini 5th"],
  },

  // Lunge intensity (education)
  {
    id: "ex_lunge_tempo",
    name: "How to Intensify a Lunge — Tempo",
    description: "Use slower eccentrics, pauses, and asymmetrical tempos.",
    muscleGroups: ["legs", "glutes"],
    series: "Lunge Coaching",
    defaultMetric: "time",
    defaultTimeSec: 30,
    equipment: EQ,
    level: "all",
    supportedPositions: [...ALL_POSITIONS],
    tags: ["coaching", "education"],
  },
  {
    id: "ex_lunge_variation",
    name: "How to Intensify a Lunge — Variation",
    description: "Adjust stance width, foot/hand positions, and range.",
    muscleGroups: ["legs", "glutes"],
    series: "Lunge Coaching",
    defaultMetric: "time",
    defaultTimeSec: 30,
    equipment: EQ,
    level: "all",
    supportedPositions: [...ALL_POSITIONS],
    tags: ["coaching", "education"],
  },
  {
    id: "ex_lunge_progression",
    name: "How to Intensify a Lunge — Progression",
    description: "Progress from supported to longer lever/giant patterns.",
    muscleGroups: ["legs", "glutes"],
    series: "Lunge Coaching",
    defaultMetric: "time",
    defaultTimeSec: 30,
    equipment: EQ,
    level: "all",
    supportedPositions: [...ALL_POSITIONS],
    tags: ["coaching", "education"],
  },

  // =========================
  // TWISTS / SIDE PLANK / OBLIQ
  // =========================
  {
    id: "ex_twist",
    name: "Twist",
    description: "Rotational core; move from ribs; hips square.",
    muscleGroups: ["obliques", "core"],
    series: "Twist",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_kneeling_torso_twist",
    name: "Kneeling Torso Twist",
    description: "Tall kneeling; rotate through thoracic spine only.",
    muscleGroups: ["obliques", "core", "back"],
    series: "Torso Twist",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "beginner",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_twister",
    name: "Twister",
    description: "Dynamic rotation under tension; control the carriage.",
    muscleGroups: ["obliques", "core"],
    series: "Twister",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "advanced",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_french_twist",
    name: "French Twist",
    description: "Oblique rotation with long lever; keep hips stable.",
    muscleGroups: ["obliques", "core"],
    series: "Twister",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "advanced",
    supportedPositions: [...ALL_POSITIONS],
  },

  // Side Plank variants
  {
    id: "ex_side_plank",
    name: "Side Plank",
    description: "Stack shoulders/hips; lift waist; keep neck long.",
    muscleGroups: ["obliques", "core", "shoulders"],
    series: "Side Plank",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: [...EQ, ...EQ_FLOOR],
    level: "beginner",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_side_plank_elbow_knee",
    name: "Side Plank on Elbow and Knee",
    description: "Modified base; focus on waist lift and alignment.",
    muscleGroups: ["obliques", "core"],
    series: "Side Plank",
    defaultMetric: "time",
    defaultTimeSec: 40,
    equipment: [...EQ, ...EQ_FLOOR],
    level: "beginner",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_side_plank_elbow_feet",
    name: "Side Plank on Elbow and Feet",
    description: "Stronger base demand; stack joints and breathe.",
    muscleGroups: ["obliques", "core"],
    series: "Side Plank",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: [...EQ, ...EQ_FLOOR],
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_side_plank_hand_knee",
    name: "Side Plank on Hand and Knee",
    description: "Bottom knee down; shoulder packs, ribs in.",
    muscleGroups: ["obliques", "core", "shoulders"],
    series: "Side Plank",
    defaultMetric: "time",
    defaultTimeSec: 40,
    equipment: [...EQ, ...EQ_FLOOR],
    level: "beginner",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_side_plank_hand_feet",
    name: "Side Plank on Hand and Feet",
    description: "Long lever lateral line; avoid shoulder collapse.",
    muscleGroups: ["obliques", "core", "shoulders"],
    series: "Side Plank",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: [...EQ, ...EQ_FLOOR],
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_reverse_side_plank",
    name: "Reverse Side Plank",
    description: "Face back; open chest; squeeze glutes to lift.",
    muscleGroups: ["obliques", "core", "back"],
    series: "Side Plank",
    defaultMetric: "time",
    defaultTimeSec: 40,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_reverse_giant_side_plank_elbow_knee",
    name: "Reverse Giant Side Plank (Elbow + Knee)",
    description: "Back platform/reverse; modified base to learn alignment.",
    muscleGroups: ["obliques", "core"],
    series: "Side Plank",
    defaultMetric: "time",
    defaultTimeSec: 40,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
    aliases: ["Giant Reverse Side Plank (Elbow+Knee)"],
  },
  {
    id: "ex_reverse_giant_side_plank_elbow_feet",
    name: "Reverse Giant Side Plank (Elbow + Feet)",
    description: "Back platform/reverse; long lever lateral line strength.",
    muscleGroups: ["obliques", "core"],
    series: "Side Plank",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "advanced",
    supportedPositions: [...ALL_POSITIONS],
    aliases: ["Giant Reverse Side Plank (Elbow+Feet)"],
  },
  {
    id: "ex_giant_side_plank_elbow_knee",
    name: "Giant Side Plank (Elbow + Knee)",
    description: "Back platform facing front; modified long lever.",
    muscleGroups: ["obliques", "core"],
    series: "Side Plank",
    defaultMetric: "time",
    defaultTimeSec: 40,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_giant_side_plank_hand_knee",
    name: "Giant Side Plank (Hand + Knee)",
    description: "Hand support; hips lifted; stack shoulder over wrist.",
    muscleGroups: ["obliques", "core", "shoulders"],
    series: "Side Plank",
    defaultMetric: "time",
    defaultTimeSec: 40,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
  },

  // Scrambled Eggs / Froggy Kicks
  {
    id: "ex_scrambled_eggs",
    name: "Scrambled Eggs",
    description: "Core + hip pattern; keep pelvis steady, ribs in.",
    muscleGroups: ["core", "obliques", "glutes"],
    series: "Obliques",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_froggy_kicks",
    name: "Froggy Kicks",
    description: "Abduction/hip external rotation with core control.",
    muscleGroups: ["glutes", "core"],
    series: "Glutes",
    unilateral: true,
    defaultMetric: "time",
    defaultTimeSec: 40,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
  },

  // Side Torso / Twisted Series
  {
    id: "ex_side_torso_twists",
    name: "Side Torso Twists",
    description: "Seated or kneeling rotation; tall spine; small ranges.",
    muscleGroups: ["obliques", "core", "back"],
    series: "Side Torso",
    defaultMetric: "time",
    defaultTimeSec: 40,
    equipment: EQ,
    level: "beginner",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_side_torso_crunch",
    name: "Side Torso Crunch",
    description: "Lateral flexion; keep opposite hip heavy.",
    muscleGroups: ["obliques", "core"],
    series: "Side Torso",
    defaultMetric: "time",
    defaultTimeSec: 40,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_twisted_plank",
    name: "Twisted Plank",
    description: "Rotational plank; hips stable; rotate from ribs.",
    muscleGroups: ["obliques", "core"],
    series: "Twisted Series",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_twisted_wheelbarrow",
    name: "Twisted Wheelbarrow",
    description: "Wheelbarrow with controlled trunk rotation.",
    muscleGroups: ["obliques", "core", "arms"],
    series: "Twisted Series",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_twisted_saw_elbows_knees",
    name: "Twisted Saw on Elbows and Knees",
    description: "Add thoracic rotation to modified Saw; small, precise.",
    muscleGroups: ["obliques", "core", "back"],
    series: "Twisted Series",
    defaultMetric: "time",
    defaultTimeSec: 40,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_bear_with_oblique_twist",
    name: "Bear with Oblique Twist",
    description: "Bear pattern with trunk rotation; hips steady.",
    muscleGroups: ["obliques", "core"],
    series: "Twisted Series",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_twisted_catfish_same",
    name: "Twisted Catfish (Same Side)",
    description: "C-curve with same-side rotation; ribs to hips.",
    muscleGroups: ["obliques", "core"],
    series: "Twisted Series",
    defaultMetric: "time",
    defaultTimeSec: 40,
    equipment: EQ,
    level: "advanced",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_twisted_catfish_alt",
    name: "Twisted Catfish (Alternating)",
    description: "Alternate rotation sides; control the return.",
    muscleGroups: ["obliques", "core"],
    series: "Twisted Series",
    defaultMetric: "time",
    defaultTimeSec: 40,
    equipment: EQ,
    level: "advanced",
    supportedPositions: [...ALL_POSITIONS],
  },

  // =========================
  // GLUTES (anatomy + drills)
  // =========================
  {
    id: "info_anatomy_gluteal",
    name: "Anatomy of the Gluteal",
    description: "Education block on glute anatomy and function.",
    muscleGroups: ["glutes", "full"],
    series: "Education",
    defaultMetric: "time",
    defaultTimeSec: 30,
    equipment: EQ_NONE,
    level: "all",
    supportedPositions: [...ALL_POSITIONS],
    tags: ["education"],
  },
  {
    id: "ex_bungee_kicks",
    name: "Bungee Kicks",
    description: "Cable kickbacks; square hips; squeeze end range.",
    muscleGroups: ["glutes", "core"],
    series: "Glutes",
    unilateral: true,
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
    tags: ["cables"],
  },
  {
    id: "ex_bungee_kicks_straight_leg",
    name: "Bungee Kicks — Straight Leg",
    description: "Long lever hip extension; avoid lumbar sway.",
    muscleGroups: ["glutes", "hamstrings"],
    series: "Glutes",
    unilateral: true,
    defaultMetric: "time",
    defaultTimeSec: 40,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
    aliases: ["Straight-Leg Bungee Kicks"],
  },
  {
    id: "ex_spider_kicks",
    name: "Spider Kicks",
    description: "External rotation glute work; control pelvis.",
    muscleGroups: ["glutes", "obliques"],
    series: "Glutes",
    unilateral: true,
    defaultMetric: "time",
    defaultTimeSec: 40,
    equipment: EQ,
    level: "advanced",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_mega_donkey_kicks",
    name: "Mega Donkey Kicks",
    description: "Hands to handles; hip extension with core brace.",
    muscleGroups: ["glutes", "core"],
    series: "Glutes",
    unilateral: true,
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "advanced",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_side_leg_press_handle",
    name: "Side Leg Press (Handle)",
    description: "Inside foot to handle; adductor/abductor patterning.",
    muscleGroups: ["glutes", "legs", "adductors", "abductors"],
    series: "Glutes",
    unilateral: true,
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_side_leg_press_footstrap",
    name: "Side Leg Press (Footstrap)",
    description: "Strap-assisted lateral press; pelvis square.",
    muscleGroups: ["glutes", "legs", "adductors", "abductors"],
    series: "Glutes",
    unilateral: true,
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
  },

  // =========================
  // ABDUCTORS
  // =========================
  {
    id: "info_anatomy_abductors",
    name: "Anatomy of the Abductors",
    description: "Education block: glute med/min and lateral line.",
    muscleGroups: ["glutes", "legs"],
    series: "Education",
    defaultMetric: "time",
    defaultTimeSec: 30,
    equipment: EQ_NONE,
    level: "all",
    supportedPositions: [...ALL_POSITIONS],
    tags: ["education"],
  },
  {
    id: "ex_standing_outer_thighs",
    name: "Standing Outer Thighs",
    description: "Lateral hip bias; maintain tall posture.",
    muscleGroups: ["glutes", "legs", "abductors"],
    series: "Abductors",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "beginner",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_skating",
    name: "Skating",
    description: "Side lunge glide; drive through standing heel.",
    muscleGroups: ["legs", "glutes", "abductors"],
    series: "Abductors",
    defaultMetric: "time",
    defaultTimeSec: 60,
    equipment: EQ,
    level: "beginner",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_skating_flat_vs_panels",
    name: "Skating — Flat vs Panels",
    description: "Compare foot placement; teach torque and control.",
    muscleGroups: ["legs", "glutes"],
    series: "Abductors",
    defaultMetric: "time",
    defaultTimeSec: 40,
    equipment: EQ,
    level: "all",
    supportedPositions: [...ALL_POSITIONS],
    tags: ["education", "drill"],
  },
  {
    id: "ex_skating_pulse",
    name: "Skating Pulse",
    description: "Micro range pulses; keep knee tracking.",
    muscleGroups: ["legs", "glutes", "abductors"],
    series: "Abductors",
    defaultMetric: "time",
    defaultTimeSec: 40,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_side_kicks",
    name: "Side Kicks",
    description: "Lateral leg raises with control; pelvis square.",
    muscleGroups: ["glutes", "abductors"],
    series: "Abductors",
    unilateral: true,
    defaultMetric: "time",
    defaultTimeSec: 40,
    equipment: EQ,
    level: "beginner",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_heavy_squats",
    name: "Heavy Squats",
    description: "Added spring; sit back; knees track over toes.",
    muscleGroups: ["legs", "glutes", "quads"],
    series: "Abductors",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
    tags: ["load"],
  },
  {
    id: "ex_single_leg_squats",
    name: "Single Leg Squats",
    description: "Unilateral squat; pelvis level; slow tempo.",
    muscleGroups: ["legs", "glutes", "quads"],
    series: "Abductors",
    unilateral: true,
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: [...EQ, ...EQ_FLOOR],
    level: "advanced",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_side_spider_kick",
    name: "Side Spider Kick",
    description: "External rotation kick with lateral line tension.",
    muscleGroups: ["glutes", "obliques", "abductors"],
    series: "Abductors",
    unilateral: true,
    defaultMetric: "time",
    defaultTimeSec: 40,
    equipment: EQ,
    level: "advanced",
    supportedPositions: [...ALL_POSITIONS],
  },

  // =========================
  // ADDUCTORS
  // =========================
  {
    id: "info_anatomy_adductors",
    name: "Anatomy of the Adductors",
    description: "Education block on inner-thigh function.",
    muscleGroups: ["legs", "adductors"],
    series: "Education",
    defaultMetric: "time",
    defaultTimeSec: 30,
    equipment: EQ_NONE,
    level: "all",
    supportedPositions: [...ALL_POSITIONS],
    tags: ["education"],
  },
  {
    id: "ex_standing_inner_thighs",
    name: "Standing Inner Thighs",
    description: "Adductor control; pelvis square; light spring.",
    muscleGroups: ["legs", "adductors"],
    series: "Adductors",
    defaultMetric: "time",
    defaultTimeSec: 60,
    equipment: EQ,
    level: "beginner",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_inner_thighs_flat_vs_panels",
    name: "Inner Thighs — Flat vs Panels",
    description: "Foot placement education; cue knee tracking.",
    muscleGroups: ["legs", "adductors"],
    series: "Adductors",
    defaultMetric: "time",
    defaultTimeSec: 40,
    equipment: EQ,
    level: "all",
    supportedPositions: [...ALL_POSITIONS],
    tags: ["education", "drill"],
  },
  {
    id: "ex_kneeling_inner_thighs",
    name: "Kneeling Inner Thighs",
    description: "Kneeling adductor pattern; trunk tall; slow return.",
    muscleGroups: ["legs", "adductors", "core"],
    series: "Adductors",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_giant_standing_inner_thighs",
    name: "Giant Standing Inner Thighs",
    description: "Back platform long lever; precise adductor tension.",
    muscleGroups: ["legs", "adductors"],
    series: "Adductors",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "advanced",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_giant_kneeling_inner_thighs",
    name: "Giant Kneeling Inner Thighs",
    description: "Kneeling + back platform; trunk tall; small ranges.",
    muscleGroups: ["legs", "adductors", "core"],
    series: "Adductors",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "advanced",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_light_squats",
    name: "Light Squats",
    description: "Reduced spring squat; emphasize depth and control.",
    muscleGroups: ["legs", "glutes", "quads"],
    series: "Adductors",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "beginner",
    supportedPositions: [...ALL_POSITIONS],
  },

  // =========================
  // HAMSTRINGS
  // =========================
  {
    id: "info_anatomy_hamstrings",
    name: "Anatomy of the Hamstrings",
    description: "Education block on posterior chain and hinge mechanics.",
    muscleGroups: ["legs", "hamstrings"],
    series: "Education",
    defaultMetric: "time",
    defaultTimeSec: 30,
    equipment: EQ_NONE,
    level: "all",
    supportedPositions: [...ALL_POSITIONS],
    tags: ["education"],
  },
  {
    id: "ex_hamstring_leg_curls",
    name: "Hamstring Leg Curls",
    description: "Prone or supine strap curls; hips extended, core on.",
    muscleGroups: ["hamstrings", "glutes", "legs"],
    series: "Hamstrings",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_giant_hamstring_leg_curls",
    name: "Giant Hamstring Leg Curls",
    description: "Back platform long lever curl; slow eccentric.",
    muscleGroups: ["hamstrings", "glutes", "legs"],
    series: "Hamstrings",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "advanced",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_reverse_giant_hamstring_leg_curls",
    name: "Reverse Giant Hamstring Leg Curls",
    description: "Reverse facing back platform; brace trunk.",
    muscleGroups: ["hamstrings", "glutes", "legs"],
    series: "Hamstrings",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "advanced",
    supportedPositions: [...ALL_POSITIONS],
    aliases: ["Giant Reverse Hamstring Curls"],
  },
  {
    id: "ex_bungee_hamstring_curls",
    name: "Bungee Hamstring Curls",
    description: "Cable-assisted curls; keep hips square.",
    muscleGroups: ["hamstrings", "glutes", "legs"],
    series: "Hamstrings",
    defaultMetric: "time",
    defaultTimeSec: 40,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
    tags: ["cables"],
  },
  {
    id: "ex_leg_curls_panels",
    name: "Leg Curls using the Panels",
    description: "Panel placement changes feel; slow, even pull.",
    muscleGroups: ["hamstrings", "glutes", "legs"],
    series: "Hamstrings",
    defaultMetric: "time",
    defaultTimeSec: 40,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
  },

  // =========================
  // QUADS
  // =========================
  {
    id: "info_anatomy_quadriceps",
    name: "Anatomy of the Quadriceps",
    description: "Education block on quad function and knee tracking.",
    muscleGroups: ["legs", "quads"],
    series: "Education",
    defaultMetric: "time",
    defaultTimeSec: 30,
    equipment: EQ_NONE,
    level: "all",
    supportedPositions: [...ALL_POSITIONS],
    tags: ["education"],
  },
  {
    id: "ex_squats",
    name: "Squats",
    description: "Sit back, chest proud; knees track over toes.",
    muscleGroups: ["legs", "glutes", "quads"],
    series: "Quads",
    defaultMetric: "time",
    defaultTimeSec: 60,
    equipment: [...EQ, ...EQ_FLOOR],
    level: "beginner",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_giant_squats_biceps",
    name: "Giant Squats with Biceps Curls",
    description: "Add cable biceps to giant squat; posture tall.",
    muscleGroups: ["legs", "glutes", "quads", "arms"],
    series: "Quads",
    defaultMetric: "time",
    defaultTimeSec: 60,
    equipment: EQ,
    level: "advanced",
    supportedPositions: [...ALL_POSITIONS],
  },

  // =========================
  // SPECIAL CONSIDERATIONS
  // =========================
  {
    id: "info_anatomy_gastrocnemius",
    name: "Anatomy of the Gastrocnemius",
    description: "Education: calf complex and ankle mechanics.",
    muscleGroups: ["legs"],
    series: "Education",
    defaultMetric: "time",
    defaultTimeSec: 30,
    equipment: EQ_NONE,
    level: "all",
    supportedPositions: [...ALL_POSITIONS],
    tags: ["education"],
  },

  // =========================
  // ABS & OBLIQUES (more)
  // =========================
  {
    id: "info_anatomy_abs",
    name: "Anatomy of the Abs",
    description: "Education on abdominal wall and breathing mechanics.",
    muscleGroups: ["core"],
    series: "Education",
    defaultMetric: "time",
    defaultTimeSec: 30,
    equipment: EQ_NONE,
    level: "all",
    supportedPositions: [...ALL_POSITIONS],
    tags: ["education"],
  },
  {
    id: "ex_s_crunch",
    name: "S-Crunch",
    description: "C-curve flexion; scoop ribs to hips; slow tempo.",
    muscleGroups: ["core"],
    series: "Abs",
    defaultMetric: "time",
    defaultTimeSec: 40,
    equipment: EQ,
    level: "beginner",
    supportedPositions: [...ALL_POSITIONS],
    aliases: ["S Crunch"],
  },
  {
    id: "ex_mega_crunch",
    name: "Mega Crunch",
    description: "C-curve ab work; slow tempo and controlled return.",
    muscleGroups: ["core"],
    series: "Abs",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "beginner",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_mega_leg_lift",
    name: "Mega Leg Lift",
    description: "Supine; posterior tilt; lift with abs, not momentum.",
    muscleGroups: ["core", "hip flexors"],
    series: "Abs",
    defaultMetric: "time",
    defaultTimeSec: 40,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_straight_arm_crunch",
    name: "Straight-Arm Crunch",
    description: "Arms long; avoid rib flare; segmental flexion.",
    muscleGroups: ["core"],
    series: "Abs",
    defaultMetric: "time",
    defaultTimeSec: 40,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_knee_strap_crunch",
    name: "Knee Strap Crunch",
    description: "Straps to knees; brace core; small ranges.",
    muscleGroups: ["core"],
    series: "Abs",
    defaultMetric: "time",
    defaultTimeSec: 40,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
    tags: ["cables"],
  },
  {
    id: "ex_leg_extensions",
    name: "Leg Extensions",
    description: "Extend from tight C-curve; lumbar supported.",
    muscleGroups: ["core", "hip flexors"],
    series: "Abs",
    defaultMetric: "time",
    defaultTimeSec: 40,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_giant_super_crunch",
    name: "Giant Super Crunch",
    description: "Back platform; longer lever C-curve crunch.",
    muscleGroups: ["core"],
    series: "Abs",
    defaultMetric: "time",
    defaultTimeSec: 40,
    equipment: EQ,
    level: "advanced",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_reverse_giant_super_crunch",
    name: "Reverse Giant Super Crunch",
    description: "Reverse facing; slow segmental curl/uncurl.",
    muscleGroups: ["core"],
    series: "Abs",
    defaultMetric: "time",
    defaultTimeSec: 40,
    equipment: EQ,
    level: "advanced",
    supportedPositions: [...ALL_POSITIONS],
    aliases: ["Giant Reverse Super Crunch"],
  },
  {
    id: "ex_giant_soul_train",
    name: "Giant Soul Train",
    description: "Advanced seated/long lever ab series; strict tempo.",
    muscleGroups: ["core"],
    series: "Abs",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "advanced",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_reverse_giant_soul_train",
    name: "Reverse Giant Soul Train",
    description: "Reverse giant variant; small, controlled ranges.",
    muscleGroups: ["core"],
    series: "Abs",
    defaultMetric: "time",
    defaultTimeSec: 45,
    equipment: EQ,
    level: "advanced",
    supportedPositions: [...ALL_POSITIONS],
    aliases: ["Giant Reverse Soul Train"],
  },
  {
    id: "ex_reverse_giant_kneeling_crunch",
    name: "Reverse Giant Kneeling Crunch",
    description: "Back platform, kneeling; tall spine, then flex.",
    muscleGroups: ["core"],
    series: "Abs",
    defaultMetric: "time",
    defaultTimeSec: 40,
    equipment: EQ,
    level: "advanced",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_giant_kneeling_crunch",
    name: "Giant Kneeling Crunch",
    description: "Kneeling long lever; control through full range.",
    muscleGroups: ["core"],
    series: "Abs",
    defaultMetric: "time",
    defaultTimeSec: 40,
    equipment: EQ,
    level: "advanced",
    supportedPositions: [...ALL_POSITIONS],
  },

  // =========================
  // ARMS – TRICEPS
  // =========================
  {
    id: "info_anatomy_triceps",
    name: "Anatomy of the Triceps",
    description: "Education on push mechanics and elbow alignment.",
    muscleGroups: ["arms"],
    series: "Education",
    defaultMetric: "time",
    defaultTimeSec: 30,
    equipment: EQ_NONE,
    level: "all",
    supportedPositions: [...ALL_POSITIONS],
    tags: ["education"],
  },
  {
    id: "ex_triceps_dips",
    name: "Triceps Dips",
    description: "Elbows track back; shoulders down; full lockout optional.",
    muscleGroups: ["arms", "shoulders"],
    series: "Triceps",
    defaultMetric: "reps",
    defaultReps: 12,
    equipment: [...EQ, ...EQ_FLOOR],
    level: "beginner",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_triceps_press_handlebars",
    name: "Triceps Press on the Handlebars",
    description: "Press down from packed shoulders; ribs in.",
    muscleGroups: ["arms", "back"],
    series: "Triceps",
    defaultMetric: "reps",
    defaultReps: 12,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_sexy_back",
    name: "Sexy Back",
    description: "Cable triceps/lat emphasis; hinge and press.",
    muscleGroups: ["arms", "back"],
    series: "Triceps",
    defaultMetric: "reps",
    defaultReps: 16,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
    aliases: ["Back Rows Triceps Combo"],
  },
  {
    id: "ex_kneeling_triceps_extension",
    name: "Kneeling Triceps Extension",
    description: "Tall kneeling; elbows pinned; full extension.",
    muscleGroups: ["arms"],
    series: "Triceps",
    defaultMetric: "reps",
    defaultReps: 12,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
  },

  // =========================
  // ARMS – BICEPS
  // =========================
  {
    id: "info_anatomy_biceps",
    name: "Anatomy of the Biceps",
    description: "Education on pull mechanics and grip.",
    muscleGroups: ["arms"],
    series: "Education",
    defaultMetric: "time",
    defaultTimeSec: 30,
    equipment: EQ_NONE,
    level: "all",
    supportedPositions: [...ALL_POSITIONS],
    tags: ["education"],
  },
  {
    id: "ex_tailbone_biceps",
    name: "Tailbone Biceps Curl",
    description: "Seated at tailbone; supinated curl; torso tall.",
    muscleGroups: ["arms"],
    series: "Biceps",
    defaultMetric: "reps",
    defaultReps: 16,
    equipment: EQ,
    level: "beginner",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_lying_biceps_curls",
    name: "Lying Biceps Curls",
    description: "Supine curl; elbows narrow; control eccentric.",
    muscleGroups: ["arms"],
    series: "Biceps",
    defaultMetric: "reps",
    defaultReps: 16,
    equipment: EQ,
    level: "beginner",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_lying_biceps_curls_lower_abs",
    name: "Lying Biceps Curls — Lower Abs",
    description: "Combine low abs engagement with curls; ribs in.",
    muscleGroups: ["arms", "core"],
    series: "Biceps",
    defaultMetric: "reps",
    defaultReps: 12,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_mega_biceps_curl",
    name: "Mega Biceps Curl",
    description: "Seated/standing cable curl; shoulders down/back.",
    muscleGroups: ["arms"],
    series: "Biceps",
    defaultMetric: "reps",
    defaultReps: 12,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_kneeling_biceps_pulldown",
    name: "Kneeling Biceps Pulldown",
    description: "Tall kneeling; pull to collar bones; lats assist.",
    muscleGroups: ["arms", "back"],
    series: "Biceps",
    defaultMetric: "reps",
    defaultReps: 12,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
  },

  // =========================
  // SHOULDERS
  // =========================
  {
    id: "info_anatomy_shoulders",
    name: "The Anatomy of the Shoulders",
    description: "Education on scapulohumeral rhythm and packing.",
    muscleGroups: ["shoulders", "back"],
    series: "Education",
    defaultMetric: "time",
    defaultTimeSec: 30,
    equipment: EQ_NONE,
    level: "all",
    supportedPositions: [...ALL_POSITIONS],
    tags: ["education"],
  },
  {
    id: "ex_chest_opener",
    name: "Chest Opener",
    description: "Open the chest with controlled cable abduction; ribs down.",
    muscleGroups: ["shoulders", "chest"],
    series: "Shoulders",
    defaultMetric: "reps",
    defaultReps: 12,
    equipment: EQ,
    level: "beginner",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_newspaper",
    name: "Newspaper",
    description: "Cable press pattern; keep ribs in, elbows soft.",
    muscleGroups: ["shoulders", "chest"],
    series: "Shoulders",
    defaultMetric: "reps",
    defaultReps: 12,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
    aliases: ["Serve the Newspaper", "Newspaper Press"],
  },
  {
    id: "ex_arm_circles",
    name: "Arm Circles",
    description: "Small controlled circles; scapulae anchored.",
    muscleGroups: ["shoulders"],
    series: "Shoulders",
    defaultMetric: "time",
    defaultTimeSec: 40,
    equipment: EQ,
    level: "beginner",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_giant_shoulder_press",
    name: "Giant Shoulder Press",
    description: "Back platform long lever press; pack shoulders.",
    muscleGroups: ["shoulders", "arms"],
    series: "Shoulders",
    defaultMetric: "reps",
    defaultReps: 12,
    equipment: EQ,
    level: "advanced",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_kneeling_shoulder_press",
    name: "Kneeling Shoulder Press",
    description: "Tall kneeling cable press; neutral wrists.",
    muscleGroups: ["shoulders", "arms"],
    series: "Shoulders",
    defaultMetric: "reps",
    defaultReps: 12,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_rear_delt_fly",
    name: "Rear Delt Fly",
    description: "Hinge; fly elbows wide; avoid upper trap dominance.",
    muscleGroups: ["shoulders", "back"],
    series: "Shoulders",
    defaultMetric: "reps",
    defaultReps: 12,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
  },

  // =========================
  // CHEST
  // =========================
  {
    id: "info_anatomy_chest",
    name: "Anatomy of the Chest",
    description: "Education on pec function and shoulder position.",
    muscleGroups: ["chest"],
    series: "Education",
    defaultMetric: "time",
    defaultTimeSec: 30,
    equipment: EQ_NONE,
    level: "all",
    supportedPositions: [...ALL_POSITIONS],
    tags: ["education"],
  },
  {
    id: "ex_upper_lift",
    name: "Upper Lift",
    description: "Cable raise with rib control; slight thoracic extension.",
    muscleGroups: ["chest", "shoulders"],
    series: "Chest",
    defaultMetric: "reps",
    defaultReps: 12,
    equipment: EQ,
    level: "beginner",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_mega_chest_fly",
    name: "Mega Chest Fly",
    description: "Wide arc fly; slight elbow bend; slow return.",
    muscleGroups: ["chest", "shoulders"],
    series: "Chest",
    defaultMetric: "reps",
    defaultReps: 12,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
    aliases: ["Chest Fly"],
  },
  {
    id: "ex_chest_press_handlebars",
    name: "Chest Press on the Handlebars",
    description: "Press from packed shoulders; neutral ribs.",
    muscleGroups: ["chest", "arms"],
    series: "Chest",
    defaultMetric: "reps",
    defaultReps: 12,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
    aliases: ["Handlebar Chest Press"],
  },

  // =========================
  // BACK
  // =========================
  {
    id: "info_anatomy_back",
    name: "The Anatomy of the Back",
    description: "Education on lat engagement and scapular control.",
    muscleGroups: ["back"],
    series: "Education",
    defaultMetric: "time",
    defaultTimeSec: 30,
    equipment: EQ_NONE,
    level: "all",
    supportedPositions: [...ALL_POSITIONS],
    tags: ["education"],
  },
  {
    id: "ex_kneeling_lat_pulldown",
    name: "Kneeling Lat Pulldown",
    description: "Tall kneeling; pull elbows to ribs; avoid rib flare.",
    muscleGroups: ["back", "arms"],
    series: "Back",
    defaultMetric: "reps",
    defaultReps: 12,
    equipment: EQ,
    level: "intermediate",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_seated_row",
    name: "Seated Row",
    description: "Neutral spine; row elbows back; slow return.",
    muscleGroups: ["back", "arms"],
    series: "Back",
    defaultMetric: "reps",
    defaultReps: 12,
    equipment: EQ,
    level: "beginner",
    supportedPositions: [...ALL_POSITIONS],
  },

  // =========================
  // STRETCHING / PULLING WITH THE TENSION
  // =========================
  {
    id: "info_stretching_note",
    name: "Note About Stretching",
    description: "General guidance on safe range, breath, and control in Lagree stretches.",
    muscleGroups: ["full"],
    series: "Stretching",
    defaultMetric: "time",
    defaultTimeSec: 20,
    equipment: EQ_NONE,
    level: "all",
    supportedPositions: [...ALL_POSITIONS],
    tags: ["education"],
  },
  {
    id: "ex_psoas_stretch",
    name: "Psoas Stretch",
    description: "Hip flexor focus; posterior pelvic tilt; gentle breath.",
    muscleGroups: ["hips", "legs"],
    series: "Stretching",
    defaultMetric: "time",
    defaultTimeSec: 30,
    equipment: [...EQ, ...EQ_FLOOR],
    level: "all",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_kneeling_hamstring_stretch",
    name: "Kneeling Hamstring Stretch",
    description: "Hinge from hips; long spine; toes up.",
    muscleGroups: ["hamstrings"],
    series: "Stretching",
    defaultMetric: "time",
    defaultTimeSec: 30,
    equipment: [...EQ, ...EQ_FLOOR],
    level: "all",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_scissor_stretch",
    name: "Scissor Stretch",
    description: "Split stance; square hips; breathe into tension.",
    muscleGroups: ["hips", "hamstrings"],
    series: "Stretching",
    defaultMetric: "time",
    defaultTimeSec: 30,
    equipment: [...EQ, ...EQ_FLOOR],
    level: "all",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_sit_and_stretch",
    name: "Sit and Stretch",
    description: "Seated hamstring/low back stretch; long spine.",
    muscleGroups: ["hamstrings", "back"],
    series: "Stretching",
    defaultMetric: "time",
    defaultTimeSec: 30,
    equipment: [...EQ, ...EQ_FLOOR],
    level: "all",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_pigeon_stretch",
    name: "Pigeon Stretch",
    description: "External rotation hip opener; keep pelvis square.",
    muscleGroups: ["glutes", "hips"],
    series: "Stretching",
    defaultMetric: "time",
    defaultTimeSec: 30,
    equipment: EQ_FLOOR,
    level: "all",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_downward_dog",
    name: "Downward Dog Stretch",
    description: "Lengthen posterior chain; press through hands; long spine.",
    muscleGroups: ["shoulders", "hamstrings", "calves"],
    series: "Stretching",
    defaultMetric: "time",
    defaultTimeSec: 30,
    equipment: EQ_FLOOR,
    level: "all",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_childs_pose",
    name: "Child's Pose",
    description: "Posterior chain decompression; slow nasal breathing.",
    muscleGroups: ["back", "hips"],
    series: "Stretching",
    defaultMetric: "time",
    defaultTimeSec: 30,
    equipment: EQ_FLOOR,
    level: "all",
    supportedPositions: [...ALL_POSITIONS],
  },

  // =========================
  // PULLING AGAINST THE TENSION (stretches with straps/tension)
  // =========================
  {
    id: "ex_v_split_stretch",
    name: "V Split Stretch",
    description: "Adductor stretch with strap/tension; gentle range.",
    muscleGroups: ["adductors"],
    series: "Stretching",
    defaultMetric: "time",
    defaultTimeSec: 30,
    equipment: EQ,
    level: "all",
    supportedPositions: [...ALL_POSITIONS],
  },
  {
    id: "ex_single_strap_hip_ham_stretch",
    name: "Single Strap Hip Ham Stretch",
    description: "Hip flexor + hamstring with single strap assistance.",
    muscleGroups: ["hips", "hamstrings"],
    series: "Stretching",
    defaultMetric: "time",
    defaultTimeSec: 30,
    equipment: EQ,
    level: "all",
    supportedPositions: [...ALL_POSITIONS],
  },
]
