import type { Exercise } from "./types"

export const lagreeExercises: Exercise[] = [
  {
    id: "1",
    name: "Plank to Pike",
    description:
      "Start in a plank position with feet on the carriage, then pike hips up while pulling the carriage in.",
    muscleGroups: ["core", "arms"],
  },
  {
    id: "2",
    name: "Reverse Lunge",
    description: "Standing on the platform, place one foot on the carriage and slide back into a lunge position.",
    muscleGroups: ["legs", "glutes"],
  },
  {
    id: "3",
    name: "French Twist",
    description: "Seated on the carriage, hold handles and rotate torso from side to side.",
    muscleGroups: ["core", "obliques"],
  },
  {
    id: "4",
    name: "Mermaid",
    description: "Seated sideways on the carriage, extend one arm overhead and stretch to the side.",
    muscleGroups: ["core", "obliques"],
  },
  {
    id: "5",
    name: "Bear",
    description: "Start on all fours with knees on the carriage, then lift knees slightly off and hold.",
    muscleGroups: ["core", "back"],
  },
  {
    id: "6",
    name: "Scrambled Eggs",
    description: "In a plank position with hands on the platform and feet on the carriage, bring knees toward chest.",
    muscleGroups: ["core", "arms"],
  },
  {
    id: "7",
    name: "Spoon",
    description: "Lie on your back on the carriage with legs extended, then curl up into a C-curve.",
    muscleGroups: ["core", "abs"],
  },
  {
    id: "8",
    name: "Wheelbarrow",
    description: "In plank position with hands on the platform and feet on the carriage, walk hands out and in.",
    muscleGroups: ["arms", "core"],
  },
  {
    id: "9",
    name: "Donkey Kicks",
    description: "On all fours with knees on the carriage, extend one leg back and up.",
    muscleGroups: ["glutes", "legs"],
  },
  {
    id: "10",
    name: "Elevator Lunges",
    description: "In a lunge position with back foot on the carriage, pulse up and down.",
    muscleGroups: ["legs", "glutes"],
  },
  {
    id: "11",
    name: "Spider Climbs",
    description: "In plank position with feet on the carriage, bring one knee toward the same-side elbow.",
    muscleGroups: ["core", "obliques"],
  },
  {
    id: "12",
    name: "Teaser",
    description: "Lie on your back on the carriage, then lift legs and upper body simultaneously into a V-shape.",
    muscleGroups: ["core", "abs"],
  },
  {
    id: "13",
    name: "Kneeling Lat Pulls",
    description: "Kneeling on the carriage, hold handles and pull down while maintaining an upright posture.",
    muscleGroups: ["back", "arms"],
  },
  {
    id: "14",
    name: "Curtsy Lunges",
    description: "Standing on the platform, place one foot on the carriage and slide into a curtsy lunge.",
    muscleGroups: ["legs", "glutes"],
  },
  {
    id: "15",
    name: "Mega Plank",
    description: "In a forearm plank position with feet on the carriage, hold and engage core.",
    muscleGroups: ["core", "arms"],
  },
  {
    id: "16",
    name: "Catfish",
    description: "Lie face down on the carriage with hands holding the front of the machine, then lift chest up.",
    muscleGroups: ["back", "core"],
  },
  {
    id: "17",
    name: "Skater Lunges",
    description: "Standing sideways on the platform, place inside foot on the carriage and slide into a side lunge.",
    muscleGroups: ["legs", "glutes"],
  },
  {
    id: "18",
    name: "Chest Press",
    description: "Kneeling or lying on the carriage, push handles forward against resistance.",
    muscleGroups: ["chest", "arms"],
  },
  {
    id: "19",
    name: "Butterfly Sit-ups",
    description: "Lie on your back on the carriage with soles of feet together, then perform a sit-up.",
    muscleGroups: ["core", "abs"],
  },
  {
    id: "20",
    name: "Rowing Series",
    description: "Seated on the carriage, hold handles and pull back while maintaining an upright posture.",
    muscleGroups: ["back", "arms"],
  },
  // Adding more Lagree exercises to ensure comprehensive coverage
  {
    id: "21",
    name: "Kneeling Arabesque",
    description: "Kneeling on the carriage with one leg extended behind you, pulse the extended leg up.",
    muscleGroups: ["glutes", "legs", "core"],
  },
  {
    id: "22",
    name: "Mermaid Crunch",
    description: "Seated sideways on the carriage, perform a side crunch while holding the handle.",
    muscleGroups: ["obliques", "core"],
  },
  {
    id: "23",
    name: "Plank Knee Tucks",
    description: "In plank position with feet on the carriage, pull knees in toward chest while keeping back flat.",
    muscleGroups: ["core", "abs"],
  },
  {
    id: "24",
    name: "Standing Arm Series",
    description: "Standing on the carriage, perform bicep curls, tricep extensions, and shoulder presses.",
    muscleGroups: ["arms", "shoulders"],
  },
  {
    id: "25",
    name: "Kneeling Side Kicks",
    description: "Kneeling on the carriage, extend one leg to the side and pulse up.",
    muscleGroups: ["glutes", "outer thighs"],
  },
  {
    id: "26",
    name: "Lagree Burpee",
    description: "Start in plank, jump feet in toward hands, then jump back out to plank position.",
    muscleGroups: ["full body", "cardio"],
  },
  {
    id: "27",
    name: "Twisted Elevator Lunge",
    description: "In a lunge position with back foot on carriage, twist torso toward front leg.",
    muscleGroups: ["legs", "glutes", "obliques"],
  },
  {
    id: "28",
    name: "Mega Oblique Crunch",
    description: "Side plank position with feet on carriage, lower and lift hips in a side crunch motion.",
    muscleGroups: ["obliques", "core"],
  },
  {
    id: "29",
    name: "Reverse Fly",
    description: "Bent over with hands holding handles, pull arms out to sides like wings.",
    muscleGroups: ["back", "shoulders"],
  },
  {
    id: "30",
    name: "Lagree Squat",
    description: "Standing on the carriage with feet wide, perform a squat while carriage moves outward.",
    muscleGroups: ["legs", "glutes", "core"],
  },
  {
    id: "31",
    name: "Tricep Dips",
    description: "Facing away from the machine, hands on platform, bend and extend elbows.",
    muscleGroups: ["triceps", "arms"],
  },
  {
    id: "32",
    name: "Lagree Cobra",
    description: "Lying face down on the carriage, lift chest and extend arms forward.",
    muscleGroups: ["back", "core"],
  },
  {
    id: "33",
    name: "Standing Split",
    description: "Standing on platform, one foot on carriage, slide leg back while hinging forward.",
    muscleGroups: ["hamstrings", "glutes"],
  },
  {
    id: "34",
    name: "Mega Crunch",
    description: "Lying on back on carriage, knees bent, perform a crunch with arms extended.",
    muscleGroups: ["abs", "core"],
  },
  {
    id: "35",
    name: "Lagree Lunge Jumps",
    description: "In lunge position with back foot on carriage, jump and switch legs in mid-air.",
    muscleGroups: ["legs", "glutes", "cardio"],
  },
]
